apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
      annotations:
        #sidecar.istio.io/inject: "false"  # ✅ Injection automatique du sidecar Istio
    spec:
      serviceAccountName: booking-app          # ✅ ici
      imagePullSecrets:
      - name: regcred                          # ✅ ici
      containers:
      - name: frontend
        image: camelia4/frontend:9.1
        ports:
        - containerPort: 80