apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: booking-reader
rules:
- apiGroups: [""] # Le groupe API core
  resources: ["pods", "services"]
  verbs: ["get", "list", "watch"]