apiVersion: apps/v1
kind: Deployment
metadata:
  name: room-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: room-service
  template:
    metadata:
      labels:
        app: room-service
      annotations:
        #sidecar.istio.io/inject: "false"
    spec:
      serviceAccountName: booking-app
      imagePullSecrets:
      - name: regcred
      containers:
      - name: room-service
        image: camelia4/room-service:1.0
        env:
        - name: DB_URL
          value: jdbc:postgresql://postgres-room:5432/roomdb
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: postgres-room-secret
              key: POSTGRES_USER
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-room-secret
              key: POSTGRES_PASSWORD
        ports:
        - containerPort: 8080