server {
    listen 80;
    server_name localhost;
    root /usr/share/nginx/html;
    index index.html;

    # Redirige toutes les requêtes vers index.html pour React Router
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Optionnel : si vous voulez proxy les appels API, mais l'Ingress le fait déjà
    # location /api/ {
    #     proxy_pass http://booking.local/api/;
    #     proxy_set_header Host booking.local;
    # }
}